@startmindmap
* 股票扫盲
 * 可投资领域
  * 股票
   * 按市场分类
    * A股: 内地上市
    * 港股: 香港上市,H股
    * 美股：美国上市
    * ST股: 高风险股票
   * 股票规模和行业地位分类
    * 大盘: 高市值公司，通常较稳定
    * 中盘：处于大、小盘之间
    * 小盘: 低市值，小公司
    * 蓝筹股：历史悠久、业绩优良、规模庞大的公司
    * 成长股：快速发展中的公司
    * 周期性股票：与经济周期密切相关
    * 防御性股票：行业通常不受一般经济周期影响
  * 债券: 发行主体
   * 国债
   * 地方债
   * 国际组织债
   * 企业债
   * 金融债
  * 货币
   * 外汇
   * 数字货币
  * 基金: 投资对象
   * 股票型
   * 债券型
   * 混合型
   * 货币市场基金
   * 指数基金
   * ETF(交易所交易基金)
   * QDII基金(境外投资)
   * FOF(基金中的基金)
  * 商品: 商品类型
   * 能源：原油、天然气、煤炭、成品油、电力
   * 金属：贵金属、基础金属、稀有金属
   * 农产品：谷物、牲畜、糖、可可
   * 特殊商品: 水资源、碳排放权、知识产权
   * 其它: 矿物、木材、珠宝
  * 金融衍生品:合约类型
   * 期权
   * 期货
   * 互换
  * 不动产: 投资项目
   * 土地
   * 住宅房地产
   * 商业房地产
   * 工业房地产
  * 货币市场工具
   * 银行定期
   * 国库券
   * 回购协议
   * 银行承兑汇票
   * 货币市场基金
   * 可转让定期存单
   * 同业拆借
 * 决定股价的因素
  * 信心
  * 公司
  * 行业
  * 宏观
 * 投资方法
  * 被低估的股票
  * 高潜力公司
  * 风险对冲
@endmindmap