@startmindmap

+ 热更新
++ Pak打包
+++ 需要确认打包的资产是否只要路径一致就可以直接应用
+++ 需要调查资源工程怎么打包

++ 内存中的资源更新
+++ 查找旧资产的所有引用，替换为新路径的资产
+++ 加载新资产，将新资产的资源赋给旧资产
+++ 查找旧资产的所有引用，标记为缓存失效，重新加载本地的资产

++ 本地的资源更新
+++ 直接loadobject时，怎么从指定的包中加载？
++++ 改写UE的资产加载方法，请求加载的是原始路径资产，但是实际返回的是新路径资产
++++ 改写UE的资产依赖查找方法，修改资产的依赖关系
++++ 提供两个更新包，分别为旧路径的新资产、新路径的新资产，标记旧资产内存缓存失效

*: 可以更新的资源类型
需要逐个检查资产的引用关系
需要逐个检查它们是否支持更新或替换;
++ 静态网格体模型
++ 骨骼网格体模型
++ 纹理
++ 材质
++ 材质实例
++ 骨骼动画

@endmindmap